version: '3.6'

services:

  rabbitmq1:
    image: rabbitmq:3.7.10-management-alpine
    hostname: rabbitmq1
    networks: 
      - rabbit
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbitmq1
    volumes:
      - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./definitions.json:/etc/rabbitmq/definitions.json"

  rabbitmq2:
    image: rabbitmq:3.7.10-management-alpine
    hostname: rabbitmq2
    networks: 
      - rabbit
    depends_on:
      - rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbitmq2
    volumes:
      - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./definitions.json:/etc/rabbitmq/definitions.json"

  rabbitmq3:
    image: rabbitmq:3.7.10-management-alpine
    hostname: rabbitmq3
    networks: 
      - rabbit
    depends_on:
      - rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbitmq3
    volumes:
      - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./definitions.json:/etc/rabbitmq/definitions.json"

  nginx:
    image: nginx:1.14-alpine
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    networks: 
      - rabbit
    ports:
      - 15672:15672
      - 5672:5672

networks:
  rabbit:
    driver: bridge